### ISSUE TITLE
finalize movement-proposals repo

### ISSUE THREAD

**Issue by christinevandev** [Govrn-HQ/Movement-Model#39]
I merged the PR update but two items to put on the radar:

1. How will communities get the repo set up that they need? Specifically they need to know to set up their repo with:
- [activity_history] folder for csvs
- activity_types.csv
- point_ranges.csv

2. It's still on testing branch, but we should move it to main 

@amsos

**Comment by amsos** [comment]
Did you resolve this with the latest update?

Or are you asking from more the mindset of how will communities edit their own repos?

**Comment by amsos** [comment]
Closing this issue as I believe we've finalized the structure.
